name: Expose Secret

on: push

jobs:
  expose-secret:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: |
          gh variable set KEY --body $KEY
        env:
          KEY: ${{ secrets.PULUMI_CONFIG_ENCRYPTION_KEY }}
